---
- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories cache and upgrade packages
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include: ./tasks/packages.yaml
    - include: ./tasks/democratic-csi-reqierments.yaml
    - include: ./tasks/users.yaml
    - include: ./tasks/cron.yaml

  handlers:
    - name: multipath-tools status
      service:
        name: multipath-tools
        state: started
    - name: open-iscsi status
      service:
        name: open-iscsi
        state: started