---
- hosts: localhost
  become: true

  pre_tasks:
    - name: update repositories cache and upgrade packages
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include: ./tasks/packages.yml