- name: install htop
  package:
    name:
      - htop
      - btop
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - qemu-guest-agent
      - gnupg2
      - ca-certificates
      - nano

- name: Enable qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: yes

- name: Start qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    state: started

- name: Run apt-get update
  apt:
    update_cache: yes
  become: yes

- name: Install apt-transport-https and iptables
  apt:
    name:
      - apt-transport-https
      - iptables
    state: present
  become: yes