- name: create Ansible user
  user:
    name: ansible
    system: yes
    state: present

- name: copy sudoers_ansible file
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
    backup: yes
